### ISSUE TITLE
Requesting multiple thousand of shared cpu cycles causes parsing error

### ISSUE THREAD

**Issue by TothFerenc** [nokia/CPU-Pooler#27]
**Describe the bug**
When we request big amount of shared cpu cycles, K8S transforms the given number to "human readable" string (for example "10000" -> "10k"), which causes a parsing error in `cpu-dev-mutator`:
```
[cloudadmin@controller-1 dpdk]$ helm install -n dpdk .
Error: release dpdk failed: admission webhook "cpu-dev-mutator.nokia.k8s.io" denied the request: strconv.Atoi: parsing "10k": invalid syntax
```

**To Reproduce**
Pod resource requests/limits: `nokia.k8s.io/shared_caas: "10000"`

**Expected behavior**
No errors.

**Comment by Levovar** [comment]
solved by https://github.com/nokia/CPU-Pooler/pull/32
