### ISSUE TITLE
Hyperthreading support

### ISSUE THREAD

**Issue by Levovar** [nokia/CPU-Pooler#31]
Just to start the discussion, and to show it is on the roadmap.

Initial ideas: automatic recognition of HT ON/OFF, report and allocate main thread + sibling thread as "one" device for exclusive pool
Or, ignore sibling threads, don't include them in the exclusive pool and only report + allocate the "main" threads

sibling threads belonging to shared and default pools should continue to work as-is

**Comment by Hu-Zhou** [comment]
This is a good idea to achieve isolated cpu pinning so only real physical core in exclusive pool is actually used even HT is enabled.
With HT on, hiding all siblings threads could be expensive. Could we learn from openstack?
Openstack offer 3 ways of cpu pinning: https://docs.openstack.org/nova/latest/admin/cpu-topologies.html#customizing-instance-cpu-thread-pinning-policies

**Comment by Levovar** [comment]
to record my current design thinking: it is clear we need at least two kind of isolation mechanisms. a guaranteed one where Pooler ensures the sibling threads are never allocated (current), and a softer one which ensures the sibling threads are not used by anonye else BUT might be used by the requesting app itself
a possible third one could be also imagined, which would be basically best effort, and would treat logical cores themselves as schedulable devices, with some effort made towards grouping them whenever possible. this is already implemented in K8s CPU Manager however, so if na app wants this -> don't use Pooler :)

so focus should be providing the first two policies. when it comes to controlling this mechanism it is clear we need a more-fine grained API than node level. the best would be if applications could use a "qualifier" in their Pod spec and tell CPU Pooler which policy to use when requesting resources from an exclusive pool.
unfortunetaly K8s Pod spec does not currently have this API (even though it was requested a couple of times in the past, it never got through SIG-Node leadership).
so we are relegated adding an additional attribute to the exclusive pool's definition, which can control this behaviour. with this method applications can still choose their desired behaviour by asking resources from the pool better suiting their need, and the level of control is still granular enough because it is already possible to define multiple exclusive pools on the same node. the problem that this approach can result in further fragmentation of the nodes' CPU sets, but there is not much we can do about it without a resource classes API unfortunetaly
