### ISSUE TITLE
About why use the pinner binary to pin cpu for a process?

### ISSUE THREAD

**Issue by andyzheung** [nokia/CPU-Pooler#33]
Hi,  I am interesting in CPU pooler and we have the same request about container also use exclusive core and share core.
    But we always pin a exclusive core to a thread in a process not only on a process, and we pass the exclusive core id to container by docker Environment and let the thread in the process pin this core by themselves. 
    Why this feature is designed only support pin a process to the exclusive core?

**Comment by TimoLindqvist** [comment]
When container asks exclusive CPUs from CPU Pooler, the CPU pooler sets the allocated CPUs (cores) to the container's environment variable `EXCLUSIVE_CPUS`. The process inside the container can do the core pinning based on this environment variable (assign the cores to the threads). 

For a use case where the process in the container is implemented by a 3rd party and CPU pinning cannot be done by the process itself, the CPU Pooler provides mechanisms to do the pinning on behalf of the process / container.

**Comment by Levovar** [comment]
so to summarize: pinning provided by the pooler is an optional feature. If you want to take care of pinning your processes to your core on your own, you can certainly do that!
otherwise, normal Linux CFS rule will take care of scheduling your threads to any of the allocated exclusive cores within your cgroup

**Comment by andyzheung** [comment]
I am really thanks for your reply, I got it! Thank you so much!@levovar@TimoLindqvist

**Comment by andyzheung** [comment]
I am really thanks for your reply, I got it! Thank you so much!@Levovar @TimoLindqvist
