### ISSUE TITLE
Is the nokia CPU Pooler can coordinate well with CPU Manager in kubernetes?

### ISSUE THREAD

**Issue by andyzheung** [nokia/CPU-Pooler#35]
In the past few days, I read more about this project. Nokia CPU Pooler can solve the problem that in a container can use exclusive cpu and shared cpu at the same time which the CPU Manager can't support.

In nokia CPU Pooler, is the following pools:
![image](https://user-images.githubusercontent.com/22912347/67162326-73346100-f395-11e9-88f7-9239d234a9af.png)

But if I use CPU Manager in kubernetes: 
![image](https://user-images.githubusercontent.com/22912347/67162408-5b111180-f396-11e9-8ef2-534fa0396def.png)

CPU Manager pool is managed by kubernetes in cpu manager.
and it allocate the exclusive core dynamical.

How Nokia CPU Pooler can coordinate with CPU Manager?  If I use CPU Pooler, I can't use CPU Manager in static mode?

**Comment by TimoLindqvist** [comment]
There is no coordination between CPU Manager and CPU Pooler. The CPU allocation must be done in one place only so if CPU Pooler is used, the CPU Manager cannot be used.

**Comment by Levovar** [comment]
if the existing static policy would be able to serve our use-case, we wouldn't have created our project :)
so yes, they are mutually exclusive.

the problems of the static policy we are trying to solve with Pooler are basically:
- not enough physically separated pools
- cores of the exclusive (pool) are randomly allocated, in run-time; which makes it impossible to optimize them for the purpose

we haven't yet given up on making the CPU Manager capable of satisfying our requirements, but practically speaking it is not on the agenda for 1.17/1.18. so for the time being workarounds are still needed

**Comment by andyzheung** [comment]
Yes, we also think that CPU Manager is not enough for our requirements. Which is evolution directions the CPU Manager in k8s? I am thinking about why this feature came from 1.7 to 1.16 but still a beta feature.

**Comment by Levovar** [comment]
you should prob ask this question in SIG-Node, rather than here :)
AFAIK SIG-Node's current focus is on improvements made to handling of hugepages, and topology manager. as the community is rather small and has a limited throughput, they would not consider additional items for the upcoming release at least

but generally speaking I'm in the process of trying to open up a dialogue again, possibly 1.18 onward. we will see how it goes
first order of business would be this: https://github.com/kubernetes/enhancements/pull/1319

**Comment by andyzheung** [comment]
Yes I see the SIG-Node is try to extend topology manager, and they plan to consider to handling hugepages and awareness of schedule,  but it will be so long to get this feature.
Any way, thank you!
