### ISSUE TITLE
Try to build docker image of webhook but the step of 'ADD Gopkg.* ./' failed

### ISSUE THREAD

**Issue by abiao610** [nokia/CPU-Pooler#45]
**Describe the bug**
Try to build docker image of the webhook based on the version of 820483a, but failed and see the following error information:

Step 7/14 : ADD Gopkg.* ./
ADD failed: no source files were specified 

**To Reproduce**
1. Checkout the source code and switch to version of 820483a ( https://github.com/nokia/CPU-Pooler/tree/820483a).
2. cd `go env GOPATH`/src/github.com/nokia/CPU-Pooler 
3. docker build -t container-infra-local.hzisoj70.china.nsn-net.net/cpu-device-webhook:820483a -f build/Dockerfile.webhook .

**Expected behavior**
Docker image get built succesfully.

**Comment by Levovar** [comment]
yeah the reason for that is the project was migrated to go module, but the Dockerfiles were not adapted to this and they still expect godep as the dependency manager
should be fixed by https://github.com/nokia/CPU-Pooler/pull/42
@eMGabriel any news on it?

**Comment by eMGabriel** [comment]
Sorry for the delayed answer. @Levovar PR #42 is ready for merge.
