### ISSUE TITLE
Build step of 'dep ensure --vendor-only' failed for not find project of Gopkg.toml

### ISSUE THREAD

**Issue by abiao610** [nokia/CPU-Pooler#48]
**Describe the bug**
After the build steps of 'Mutating webhook' and 'The device plugin', try to do 'dep ensure --vendor-only' but receives error saying "could not find project Gopkg.toml, use dep init to initiate a manifest".

**To Reproduce**
1. docker build -t ${DOCKER_REGISTRY}/cpu-device-webhook:${CPUPOOLER_VERSION} \
        -f build/Dockerfile.webhook .
2. docker build -t ${DOCKER_REGISTRY}/cpudp:${CPUPOOLER_VERSION} \
        -f build/Dockerfile.cpudp .
3. dep ensure --vendor-only

**Expected behavior**
the cmd executed successfully.

**Additional context**

**Relevant SW info**
- Linux distro
- Kubernetes version
- Other

**Comment by Levovar** [comment]
maybe pull master and re-try? :)
correction was just merged yesterday

**Comment by Levovar** [comment]
ah if you are trying to build the process starter, just ignore the "dep" part, as it is not used anymore
simply execute go build. go modules are integrated into tgo build command from 1.13 onward, so it should work seamlessly
I will correct the documentation

**Comment by abiao610** [comment]
Ok, got it. Pls close this issue.

**Comment by Levovar** [comment]
Replaced the incorrect reference to dep: https://github.com/nokia/CPU-Pooler/commit/21ee2538f9518452d5f507b0ebf4f932c18ca254
