### ISSUE TITLE
Help needed regarding cpu-pooler-configmap.yaml

### ISSUE THREAD

**Issue by shubham-gaur** [nokia/CPU-Pooler#51]
Hi, I was working with Akraino setup. This setup was already having a cpu-pooler-configmap.yaml installed in kube-system namespace. Mistakingly I have over written the same configMap. Is there a way to get the default configMap or Is it fine to overwrite the cpu-pooler-configmap present at kube-system namespace. Please let me know where I can find the default cpu-pooler-configmap that came along with Akraino installation.

**Comment by TimoLindqvist** [comment]
The configuration files in CPU pooler repo are just examples how it can be used. It's not possible to provide default configuration as it is totally dependent on used hardware setup. The configuration should have been created for the project you are working on.

**Comment by shubham-gaur** [comment]
Thanks, @TimoLindqvist... Was able to see the default config after reinstalling the setup. Is there any particular way to reset any service to its defaults present at the time of installation... *(Eg: Just like resetting only cpu-pooler services inside the cluster)*? That would be really helpful rather than resetting/ reinstalling the whole setup.

Thanks for the help!

**Comment by TimoLindqvist** [comment]
@shubham-gaur , I tried to think about the use case and possibilities for resetting the configuration back to the original. Kubernetes configuration best practices mentions storing the configuration files to version control. Maybe that is the only way to get back the original ... 

With regards to cpu pooler, the use case might be a bit complicated as there might be lots of pods dependent on cpu pooler configuration. As the configuration defines node's cpu partitioning scheme, resetting the configuration probably requires draining the node(s) so it might become rather big job anyway.
