### ISSUE TITLE
does not match to expected cpuset 

### ISSUE THREAD

**Issue by antzjm** [nokia/CPU-Pooler#68]
**Describe the bug**
Pod can not get cpu core and restart.

Used CPU Pool(s):  exclusive&shared
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) expected cpuset (4,12,24,26)
Cgroup cpuset (0-39) does not match to expected cpuset (4,12,24,26)

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Additional context**

**Relevant SW info**
release=NCI_R19-33
build=6021.ga8897f5
cpu-pooler-0.3.1-15
- Other

**Comment by antzjm** [comment]
I have seen old issue about this phenomenon. But it still happens in latest cpu-pooler version.

**Comment by antzjm** [comment]
hello ,cpu pooler support team. This issue always happened. Can you help us to detect root cause of this problem. 
here is error log:
I0621 19:41:50.486854       1 webhook.go:315] Patch container for pinning l2rt-container

**Comment by Levovar** [comment]
see https://github.com/nokia/CPU-Pooler/issues/64#issuecomment-828348095

yep it intermittently does, and will continue to do so until https://github.com/nokia/CPU-Pooler/pull/62 is concluded on

**Comment by Levovar** [comment]
#70 aims to handle this issue, testing is still pending

**Comment by Levovar** [comment]
#70 implements the required architectural change for guaranteed performance. no container restarts should be happening now during deployment

note that the request is not yet finished, as during the refactoring we needed to break the functionality ensuring restarted containers also get their desired cpuset back. feedback related to the initial deployment scenario with the new patch is appreciated though while I'm working on the next PR

**Comment by Levovar** [comment]
#73 completes the re-factoring!
please update to latest commit, and re-try. issue should not be seen again
